#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>

int main (int argc, char *argv[])
{
   MPI_Comm presentComm, nextComm;
   MPI_Group presentGroup, nextGroup;
   int gMemb[8];
   int rank, nProc, nProcNow, length, nIter;
   int *sendData = NULL, *recData;
   int i, j;

   MPI_Init (&argc, &argv);
   MPI_Comm_rank (MPI_COMM_WORLD, &rank);
   MPI_Comm_size (MPI_COMM_WORLD, &nProc);
   if (nProc > 8)
      { if (rank == 0) printf ("Too many processes! It should be a power of 2, less or equal to 8.\n");
        MPI_Finalize ();
        return EXIT_FAILURE;
      }
   length = 1 << 24;
   nIter = (int) (log2 (nProc) + 1.1);
   recData = malloc (length * sizeof (int));
   if (rank == 0)
      { sendData = malloc (length * sizeof (int));
        printf ("Data to be scattered is being generated by process %d.\n", rank);
        for (i = 0; i < length; i++)
          sendData[i] = i;
      }
   nProcNow = nProc;
   presentComm = MPI_COMM_WORLD;
   MPI_Comm_group (presentComm, &presentGroup);
   for (i = 0; i < 8; i++)
     gMemb[i] = i;
   for (j = 0; j < nIter; j++)
   { if (j > 0)
        { MPI_Group_incl (presentGroup, nProcNow, gMemb, &nextGroup);
          MPI_Comm_create(presentComm, nextGroup, &nextComm);
          presentGroup = nextGroup;
          presentComm = nextComm;
          if (rank >= nProcNow)
             { free (recData);
               MPI_Finalize ();
               return EXIT_SUCCESS;
             }
        }
     MPI_Comm_size (presentComm, &nProc);
     MPI_Scatter (sendData, length / nProcNow, MPI_INT, recData, length / nProcNow, MPI_INT, 0, presentComm);
     printf ("Scattered data received by process %d with length = %d for a group of %d process(es).\n", rank, (length / nProcNow), nProc);
     MPI_Gather (recData, length / nProcNow, MPI_INT, sendData, length / nProcNow, MPI_INT, 0, presentComm);
     if (rank == 0)
        printf ("Gathered data received by process 0 with length = %d for a group of %d process(es).\n", length, nProc);
     nProcNow = nProcNow >> 1;
   }
   MPI_Finalize ();

   return EXIT_SUCCESS;
}
